batch_size: 4
iters: 40000

train_dataset:
  type: Dataset
  num_classes: 20
  dataset_root: data/voc/VOCdevkit/VOCleather/
  train_path: data/voc/VOCdevkit/VOCleather/train.txt
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  num_classes: 20
  dataset_root: data/voc/VOCdevkit/VOCleather/
  val_path: data/voc/VOCdevkit/VOCleather/val.txt
  transforms:
    - type: Padding
      target_size: [512, 512]
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

learning_rate:
  value: 0.01
  decay:
    type: poly
    power: 0.9
    end_lr: 0.0

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
